function [fitresult, gof] = createFit(gh_z)
%CREATEFIT(GH_Z)
%  Create a fit.
%
%  Data for 'untitled fit 2' fit:
%      Y Output: gh_z
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 06-Oct-2022 19:09:40


%% Fit: 'untitled fit 2'.
[xData, yData] = prepareCurveData( [], gh_z );

% Set up fittype and options.
ft = fittype( 'smoothingspline' );
opts = fitoptions( 'Method', 'SmoothingSpline' );
opts.SmoothingParam = 0.958395796691723;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Create a figure for the plots.
figure( 'Name', 'untitled fit 2' );

% Plot fit with data.
subplot( 2, 1, 1 );
h = plot( fitresult, xData, yData );
legend( h, 'gh_z', 'untitled fit 2', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
ylabel( 'gh_z', 'Interpreter', 'none' );
grid on

% Plot residuals.
subplot( 2, 1, 2 );
h = plot( fitresult, xData, yData, 'residuals' );
legend( h, 'untitled fit 2 - residuals', 'Zero Line', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
ylabel( 'gh_z', 'Interpreter', 'none' );
grid on


