function DataViewer(varargin)
% This function opens a figure which can be used through navigate through
% the kinematic data. When a filename of a MAT-file that contains kinematic
% data is provided as input, the file is automatically opened and loaded.
% If no input arguments are given, the user can browse to a file to load
% it.
% Coded by Bart Bolsterlee (b.bolsterlee@tudelft.nl)
% September 2014


% Add current path to search path
% addpath(pwd);

% Stop complaining about too little room for legend...
warning off

fontsize = 9;
fontweight = 'normal';

set(0,'DefaultAxesFontSize',fontsize)
set(0,'DefaultAxesFontWeight',fontweight)
set(0,'DefaultTextFontSize',fontsize)
set(0,'DefaultTextFontWeight',fontweight)

% Make figure and axes
f = figure('Name', '3D animation of landmark trajectories',...
   'NumberTitle', 'off',...
   'Units','Pixels',...
   'Color', [0.8 0.8 0.8],...
   'ResizeFcn', 'PlotFun(''Resize'')');


figdim = [900 500];
set(f,'Position',[50 50 figdim]) 

% Create GUI
fPos = get(f, 'Position');
bgColor = [0.8 0.8 0.8];

% Play button
uicontrol('Style', 'Toggle',...
   'String', 'Play',...
   'HorizontalAlignment','Center',...
   'BackgroundColor', bgColor,...   
   'UserData', 1,...
   'Callback','PlotFun(''Play'')',...
   'Tag','PlayButton',...
   'Enable','Off',...
   'TooltipString','Click to play animation')
% Textbox for frame
uicontrol('Style', 'Text',...
   'String', 'Frame:',...
   'HorizontalAlignment','Left',...
   'BackgroundColor', bgColor,...   
   'UserData', 1,...
   'Tag','FrameNr')
% Edit box for frame
uicontrol('Style', 'Edit',...
   'String', '',...
   'HorizontalAlignment','Left',...
   'BackgroundColor', [1 1 1],...   
   'UserData', 1,...
   'Tag','FrameNrInput',...
   'CallBack','PlotFun(''SetFrame'')')
% Slider
uicontrol('Style','Slider',...
    'BackgroundColor',[1 1 1],...
    'Callback','PlotFun(''Slider'')',...
    'Tag','Slider',...
    'Userdata',1,...
    'Enable','Off');
% Main axes window with 3-D view of landmarks
axes('Units','pixels',...
    'Visible','off',...
    'Color',[1 1 1],...
    'Tag','MainAxes',...
    'NextPlot','replacechildren');
% Text box
uicontrol('Style', 'Text',...
   'String', 'File: ',...
   'HorizontalAlignment','Left',...
	'BackgroundColor', bgColor,...
	'UserData', 2,...
    'Tag','TextBox')
% Displays name of selected file.
uicontrol('Style', 'Edit',...
   'Tag', 'inputModel',...
   'HorizontalAlignment', 'left',...
   'BackgroundColor', [1 1 1],...
   'CallBack', 'PlotFun(''InputModel'')',...
   'UserData', 2)
% Button to load a file
uicontrol('Style', 'PushButton',...
   'Tag', 'browseModel',...
   'String', '...',...
   'CallBack', 'PlotFun(''BrowseModel'')',...
   'UserData', 2,...
   'BackGroundColor',bgColor)

% Dropdown-menu for segment rotations
MenuEntries = {'Thorax wrt global',...
           'Clavicle wrt thorax',...
           'Scapula wrt thorax',...
           'Scapula locator wrt thorax',...
           'Humerus wrt thorax',...
           'Forearm wrt humerus'};

uicontrol('Style','popupmenu',...
          'Tag','Popup1',...
          'String',MenuEntries,...
          'CallBack', 'PlotFun(''SegmRot1'')',...
          'Enable','off');
% Text box      
uicontrol('Style','Text',...
          'String','Select segment rotations to plot',...
          'Tag','PopupText1',...
          'BackGroundColor',bgColor)
% Axes for segment rotations
axes('Units','pixels',...
    'Visible','off',...
    'Color',[1 1 1],...
    'Tag','SegmRotAxes',...
    'NextPlot','replacechildren',...
    'ButtonDownFcn','PlotFun(''ShiftCurrentPos'')');
% Button to display coordinate systems
uicontrol('Units','Pixels',...
    'Enable','off',...
    'BackGroundColor',bgColor,...
    'Tag','PlotDirVec',...
    'CallBack','PlotFun(''PlotCoordSys'')',...
    'String','Plot coordinate systems',...
    'TooltipString','Click to plot local coordinate system in current frame')
% Button to show landmark names
uicontrol('Units','Pixels',...
    'Enable','off',...
    'BackGroundColor',bgColor,...
    'Tag','ShowLandmarkLabel',...
    'CallBack','PlotFun(''ShowLandmarkLabel'')',...
    'String','Show Landmark Labels',...
    'TooltipString','Click to show landmark names')

% If a filename is provided as input argument, load this file.
if nargin==1
    fileName = varargin{1};
    PlotFun('LoadModel',fileName)
end

PlotFun('Resize')
end